# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "CARTS" ("ORDER_ID" BIGINT NOT NULL,"PRODUCT_ID" BIGINT NOT NULL,"QUANTITY" INTEGER NOT NULL);
create table "ORDERS" ("ORDER_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"TOTAL" DOUBLE NOT NULL,"STATUS" VARCHAR NOT NULL);
create table "PRODUCTS" ("PRODUCT_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"NAME" VARCHAR NOT NULL,"PRICE" DOUBLE NOT NULL,"STOCK" BIGINT NOT NULL);
alter table "CARTS" add constraint "ORDER_FK" foreign key("ORDER_ID") references "ORDERS"("ORDER_ID") on update NO ACTION on delete NO ACTION;
alter table "CARTS" add constraint "PRODUCT_FK" foreign key("PRODUCT_ID") references "PRODUCTS"("PRODUCT_ID") on update NO ACTION on delete NO ACTION;

# --- !Downs

alter table "CARTS" drop constraint "ORDER_FK";
alter table "CARTS" drop constraint "PRODUCT_FK";
drop table "PRODUCTS";
drop table "ORDERS";
drop table "CARTS";

